//
// Generated by JTB 1.3.2
//

package spiglet.visitor;
import java.util.Enumeration;

import spiglet.spiglet2kanga.CMethod;
import spiglet.spiglet2kanga.CStmt;
import spiglet.spiglet2kanga.Environment;
import spiglet.syntaxtree.BinOp;
import spiglet.syntaxtree.CJumpStmt;
import spiglet.syntaxtree.Call;
import spiglet.syntaxtree.ErrorStmt;
import spiglet.syntaxtree.Exp;
import spiglet.syntaxtree.Goal;
import spiglet.syntaxtree.HAllocate;
import spiglet.syntaxtree.HLoadStmt;
import spiglet.syntaxtree.HStoreStmt;
import spiglet.syntaxtree.IntegerLiteral;
import spiglet.syntaxtree.JumpStmt;
import spiglet.syntaxtree.Label;
import spiglet.syntaxtree.MoveStmt;
import spiglet.syntaxtree.NoOpStmt;
import spiglet.syntaxtree.Node;
import spiglet.syntaxtree.NodeList;
import spiglet.syntaxtree.NodeListOptional;
import spiglet.syntaxtree.NodeOptional;
import spiglet.syntaxtree.NodeSequence;
import spiglet.syntaxtree.NodeToken;
import spiglet.syntaxtree.Operator;
import spiglet.syntaxtree.PrintStmt;
import spiglet.syntaxtree.Procedure;
import spiglet.syntaxtree.SimpleExp;
import spiglet.syntaxtree.Stmt;
import spiglet.syntaxtree.StmtExp;
import spiglet.syntaxtree.StmtList;
import spiglet.syntaxtree.Temp;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class LivenessVisitor extends GJDepthFirst<String, Environment> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String visit(NodeList n, Environment argu) {
      String _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeListOptional n, Environment argu) {
      if ( n.present() ) {
         String _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public String visit(NodeOptional n, Environment argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public String visit(NodeSequence n, Environment argu) {
      String _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeToken n, Environment argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public String visit(Goal n, Environment argu) {
      argu.currentMethod = new CMethod("MAIN");
      argu.currentMethod.nParaSize = 0;
      argu.currentMethod.addStmt(new CStmt("empty"));
      n.f1.accept(this, argu);
      argu.addMethod();
      
      n.f3.accept(this, argu);
      
      return null;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public String visit(StmtList n, Environment argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public String visit(Procedure n, Environment argu) {
	  String _ret=null;
	  argu.currentMethod = new CMethod(n.f0.f0.tokenImage);
	  argu.currentMethod.nParaSize = Integer.valueOf(n.f2.f0.tokenImage);
	  argu.currentMethod.addStmt(new CStmt("empty"));
	  
      n.f4.accept(this, argu);
      argu.addMethod();
      
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public String visit(Stmt n, Environment argu) {
      String _ret = null;
      argu.isInStmt = true;
      n.f0.accept(this, argu);
      argu.isInStmt = false;
      
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public String visit(NoOpStmt n, Environment argu) {
      String _ret=null;
      CStmt stmt = new CStmt("NoOpStmt");
      argu.currentMethod.addStmt(stmt);

      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public String visit(ErrorStmt n, Environment argu) {
      String _ret=null;
      CStmt stmt = new CStmt("ErrorStmt");
      argu.currentMethod.addStmt(stmt);

      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public String visit(CJumpStmt n, Environment argu) {
      String _ret=null;
      CStmt stmt = new CStmt("CJumpStmt");
      stmt.jumpLabel = n.f2.f0.tokenImage;
      stmt.addUsedTemp(n.f1.f1.f0.tokenImage);
      argu.currentMethod.addStmt(stmt);
      
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public String visit(JumpStmt n, Environment argu) {
      String _ret=null;
      CStmt stmt = new CStmt("JumpStmt");
      stmt.jumpLabel = n.f1.f0.tokenImage;
      stmt.isUnconditionJump = true;
      argu.currentMethod.addStmt(stmt);
      
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public String visit(HStoreStmt n, Environment argu) {
	   String _ret=null;
	   CStmt stmt = new CStmt("HStoreStmt");
	   stmt.addUsedTemp(n.f1.f1.f0.tokenImage);
	   stmt.addUsedTemp(n.f3.f1.f0.tokenImage);
	   argu.currentMethod.addStmt(stmt);
      
	   return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public String visit(HLoadStmt n, Environment argu) {
	   String _ret=null;
	   CStmt stmt = new CStmt("HLoadStmt");
	   stmt.addUsedTemp(n.f1.f1.f0.tokenImage);
	   stmt.addUsedTemp(n.f2.f1.f0.tokenImage);
	   argu.currentMethod.addStmt(stmt);

	   return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public String visit(MoveStmt n, Environment argu) {
	   String _ret=null;
	   argu.currentStmt = new CStmt("MoveStmt");
	   argu.currentStmt.genTemp = Integer.valueOf(n.f1.f1.f0.tokenImage);
	   n.f2.accept(this, argu);
	   argu.currentMethod.addStmt(argu.currentStmt);
	   
	   return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public String visit(PrintStmt n, Environment argu) {
	   String _ret=null;
	   argu.currentStmt = new CStmt("PrintStmt");
	   n.f1.accept(this, argu);
	   argu.currentMethod.addStmt(argu.currentStmt);
	   
	   return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public String visit(Exp n, Environment argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public String visit(StmtExp n, Environment argu) {
      String _ret=null;
      n.f1.accept(this, argu);
      
      argu.currentStmt = new CStmt("Return"); 
      n.f3.accept(this, argu);
      argu.currentMethod.addStmt(argu.currentStmt);
	   
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public String visit(Call n, Environment argu) {
      String _ret=null;
      argu.currentStmt = new CStmt("Call"); 
      n.f1.accept(this, argu);
      n.f3.accept(this, argu);
      argu.currentMethod.addStmt(argu.currentStmt);
      
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public String visit(HAllocate n, Environment argu) {
      String _ret=null;
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public String visit(BinOp n, Environment argu) {
      String _ret=null;
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "LT"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    */
   public String visit(Operator n, Environment argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public String visit(SimpleExp n, Environment argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public String visit(Temp n, Environment argu) {
      String _ret=null;
      argu.currentStmt.addUsedTemp(n.f1.f0.tokenImage);
      
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, Environment argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Label n, Environment argu) {
      String _ret=null;
      if (argu.isInStmt) {
    	  argu.currentStmt.jumpLabel = n.f0.tokenImage;
      } else {
    	  CStmt stmt = new CStmt("Entry Label");
    	  stmt.entryLabel = n.f0.tokenImage;
    	  argu.currentMethod.addStmt(stmt);
      }
      
      return _ret;
   }

}
